### ISSUE TITLE
C'est pas très commenté tout ça

### ISSUE THREAD

**Issue by KNaudin** [Orann/ia_work2#1]
Tout est en dans le titre

**Comment by Orann** [comment]
Haha, tranquille, on a fait que deux commits et on s'est vraiment focalisé sur les algo. On est pas fou, on a un beau brouillon commenté, les commentaires codés arrivent bientôt ! ;)

**Comment by KNaudin** [comment]
Ouais ouais c'est ce qu'ils disent tous

**Comment by Orann** [comment]
J'avoue, en plus au final on s'est rendu compte que notre code était tellement parfait qu'il se suffisait à lui-même, pas besoin de commentaire comme ils le disent tous si bien ! ;) Mais on a quand même rajouté des petites explications avec un PDF. :)
Je ferme donc cette issue que ça te plaise ou non ! ;)
